import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'

export default function Home() {


  return (
    <>
      <Head>
        <title>Wendy Chen Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>

        <NavBar />

        <h1 className={`${styles.title}`}>Projects</h1>

        <div className={`${styles.layout}`}>
          <div>
            <img className={`${styles.image}`} src='/images/whitestone-cover.jpg' />
          </div>
          <div>
            <h1>WhiteStone</h1>
            <p>WhiteStone is a machine learning dental scanning app for low income and colourblind people to help users evaluate their dental health to reduce the number of dental checkups. It takes pictures of people's mouths and provides data on the teeth scan results.</p>
            <button className={`${styles.button}`}><a href='/whitestone'>Learn More</a></button>
          </div>
        </div>

        <div className={`${styles.layout}`}>
          <div>
            <img className={`${styles.image}`} src='/images/drugminder.png' />
          </div>
          <div>
            <h1>DrugMinder</h1>
            <p>DrugMinder is a free mobile app that allows users to test for overdosing on cocaine, MDMA, and alcohol. It also provides information for users to learn more about the drugs, including recommended dosages, symptoms of overdosing, and precautions.</p>

            <button className={`${styles.button}`}><a href='/drugminder'>Learn More</a></button>
          </div>
        </div>

        <div className={`${styles.layout}`}>
          <div>
            <img className={`${styles.image}`} src='/images/tinypaws-proto-screen.png' />
          </div>
          <div>
            <h1>TinyPaws</h1>
            <p>Tinypaws is a cat adoption website that believes every cat deserves a loving home. It was designed to be used on WordPress and fulfill the client's style requirements.</p>
            <button className={`${styles.button}`}><a href='/tinypaws'>Learn More</a></button>
          </div>
        </div>

        <div className={`${styles.layout}`}>
          <div>
            <img className={`${styles.image}`} src='/images/soda.png' />
          </div>
          <div>
            <h1>Frezz</h1>
            <p>Tinypaws is a cat adoption website that believes every cat deserves a loving home. It was designed to be used on WordPress and fulfill the client's style requirements.</p>
            <button className={`${styles.button}`}><a href='/frezz'>Learn More</a></button>
          </div>
        </div>

        <Footer />
      </main>
    </>
  )
}
